In [1]:
#1. Дан произвольный список, содержащий только числа. Выведите результат сложения всех чисел больше 10. 
import random

random_numbers = []
for i in range(0,7):
    x = random.randint(1,50)
    random_numbers.append(x)

sum_of_numbers = 0
for number in random_numbers:
    if number > 10:
        sum_of_numbers += number
        
print('Наш список: {}, сумма элементов больших 10: {}'.format(random_numbers, sum_of_numbers))

Наш список: [15, 16, 40, 24, 26, 47, 49], сумма элементов больших 10: 217


In [2]:
#1.1
import numpy as np
numpy_numbers = np.array(random_numbers)
greater_10 = numpy_numbers[numpy_numbers>10]
sum_of_numbers = sum(greater_10)
print('Наш список: {}, сумма элементов больших 10: {}'.format(random_numbers, sum_of_numbers))

Наш список: [15, 16, 40, 24, 26, 47, 49], сумма элементов больших 10: 217


In [3]:
#2. Пусть задан список, содержащий строки. Выведите все строки, заканчивающиеся буквой r.

data = ['title', 'film', 'dwdw ww ddwwr','waaaes sa sssddr', 'wwaas dds vvrraaw']

#первый способ
for string in data:
    if string.endswith('r'):
        print(string)

#второй способ
for string in data:
    if string[len(string)-1:] == 'r':
        print(string)

dwdw ww ddwwr
waaaes sa sssddr
dwdw ww ddwwr
waaaes sa sssddr


In [4]:
#3. Сгенерируйте и выведите cлучайную строку размером 6 символов, содержащую только цифры. Строка должна
#содержать хотя бы одну цифру 3
import random
string_length = 6

def string_with_random_numbers(string_length):
    list_of_numbers = []
    for i in range(0,string_length):
        x = random.randint(0,9)
        list_of_numbers.append(str(x))
        
    if '3' in list_of_numbers:
        return ''.join(list_of_numbers)
    else:
        print('Yes')
        x = random.randint(0,string_length-1)
        list_of_numbers[x] = '3'
        return ''.join(list_of_numbers)

string_with_random_numbers(string_length)

'377655'

In [5]:
#4. Пусть дана строка произвольной длины. Выведите информацию о том, сколько в ней символов и сколько слов.

string = 'wweqe, qwe wqwqewse. Wwqqq, ioi, wwqsdas, z ytwwe -! ReR!'
print('Наша строка: ', string)
print('Количество символов с разделителями', len(string))

#получим список из слов без разделителей
words = string.replace('.',' ').replace(',',' ').replace('!',' ').replace('-',' ').split()

words_count = len(words) #количество слов

joined_string = ''.join(words) #получаем строку без разделителей

print('Наша строка без разделителей: {}'.format(joined_string))
print('Количество символов без разделителей: {}, Количество слов: {}.'.format(len(joined_string), words_count))
print('Слова: {}'.format(words))

Наша строка:  wweqe, qwe wqwqewse. Wwqqq, ioi, wwqsdas, z ytwwe -! ReR!
Количество символов с разделителями 57
Наша строка без разделителей: wweqeqwewqwqewseWwqqqioiwwqsdaszytwweReR
Количество символов без разделителей: 40, Количество слов: 9.
Слова: ['wweqe', 'qwe', 'wqwqewse', 'Wwqqq', 'ioi', 'wwqsdas', 'z', 'ytwwe', 'ReR']


In [6]:
#4.1. Более универсальный вариант.
from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer(r'\w+')
words = tokenizer.tokenize(string)
joined_string = ''.join(words)
print('Наша строка без разделителей: {}'.format(joined_string))
print('Количество символов без разделителей: {}, Количество слов: {}.'.format(len(joined_string), words_count))
print('Слова: {}'.format(words))

Наша строка без разделителей: wweqeqwewqwqewseWwqqqioiwwqsdaszytwweReR
Количество символов без разделителей: 40, Количество слов: 9.
Слова: ['wweqe', 'qwe', 'wqwqewse', 'Wwqqq', 'ioi', 'wwqsdas', 'z', 'ytwwe', 'ReR']


In [7]:
#1. Пусть дана матрица чисел размером NхN. Представьте данную матрицу в виде списка. Выведите результат сложения
#всех элементов матрицы.

import random
#создадим матрицу случайных элементов от 1 до 50 с помощью random. Обернем это в отдельную функцию
def matrix(N, M):
    matrix = []
    i = 0
    for i in range(0,N):
        list_of_numbers = []
    
        for i in range(0,M):
            x = random.randint(1,50)
            list_of_numbers.append(x)
        
        matrix.append(list_of_numbers)
    return matrix

In [8]:
N = int(input('Введите число размер матрицы N: ', ))

#теперь посчитаем сумму всех ее элементов
elements_sum = 0
for string in matrix(N, N):
    elements_sum += sum(string)

print('Наша матрица NxN: {}'.format(matrix(N,N)))
print('Cумма элементов матрицы: {}'.format(elements_sum))

Введите число размер матрицы N: 4
Наша матрица NxN: [[25, 43, 29, 6], [34, 5, 18, 13], [39, 2, 41, 35], [24, 7, 16, 44]]
Cумма элементов матрицы: 430


In [9]:
#1.1. Вариант с numpy.
import numpy as np
N = int(input('Введите число размер матрицы N: ', ))

matrix_rand = np.random.randint(1, 50, (N, N))
array = matrix_rand.flatten()
print('Наша матрица NxN: \n{}'.format(matrix_rand))
print('Cумма элементов матрицы: {}'.format(sum(array)))

Введите число размер матрицы N: 4
Наша матрица NxN: 
[[39 15 43 49]
 [40  7 44 12]
 [47 34 17 33]
 [22  6  1 40]]
Cумма элементов матрицы: 449


In [10]:
#2. Пусть дана матрица чисел размером NхM. Найти столбец матрицы с максимальной суммой элементов.

N = int(input('Введите число строк матрицы N: ', ))
M = int(input('Введите число столбцов матрицы M: ', ))

n_matrix = matrix(N, M)

#транспонируем матрицу с помощью zip
transposed_matrix = list(zip(*n_matrix))
max_sum = 0
for string in transposed_matrix:
    if sum(string) > max_sum:
        max_sum = sum(string)
        max_column = string

print('Cамая большая сумма элементов в столбцах: {}, сам слолбец: {}.'.format(max_sum, max_column))
print('Транспонированная матрица: {}'.format(transposed_matrix))
print('Изначальная матрица: {}'.format(n_matrix))

Введите число строк матрицы N: 4
Введите число столбцов матрицы M: 5
Cамая большая сумма элементов в столбцах: 128, сам слолбец: (28, 43, 33, 24).
Транспонированная матрица: [(39, 8, 29, 37), (41, 20, 34, 13), (32, 36, 2, 34), (28, 43, 33, 24), (37, 26, 37, 7)]
Изначальная матрица: [[39, 41, 32, 28, 37], [8, 20, 36, 43, 26], [29, 34, 2, 33, 37], [37, 13, 34, 24, 7]]


In [11]:
#2.1. Вариант с использованием numpy.
import numpy as np
N = int(input('Введите число строк матрицы N: ', ))
M = int(input('Введите число столбцов матрицы M: ', ))

matrix_rand = np.random.randint(1, 50, (N, M))
number = matrix_rand.sum(axis=0).argmax()
max_column = matrix_rand.T[number]

print('Cамая большая сумма элементов в столбцах: {}, сам слолбец: {}.'.format(sum(max_column), max_column))
print('Изначальная матрица: \n{}'.format(matrix_rand))
print('Транспонированная матрица: \n{}'.format(matrix_rand.T))

Введите число строк матрицы N: 4
Введите число столбцов матрицы M: 5
Cамая большая сумма элементов в столбцах: 131, сам слолбец: [38 38 47  8].
Изначальная матрица: 
[[19 15 38  5 11]
 [ 6 11 38 20  3]
 [27 44 47 27 13]
 [43 46  8 15  6]]
Транспонированная матрица: 
[[19  6 27 43]
 [15 11 44 46]
 [38 38 47  8]
 [ 5 20 27 15]
 [11  3 13  6]]


In [12]:
#1. Пусть список студентов представлен в виде структуры [[No, ФИО, Возраст,Группа],[No, ФИО, Возраст, Группа],[No, ФИО,
#Возраст, Группа]]. Преобразуйте список в словарь вида: {No: [ФИО, Возраст, Группа], No:[....], No: [....]}

data = [[1, 'Иванов', 18, 'НФ-101'], [2, 'Свердлов', 20, 'НФ-301'],[3, 'Сидоров', 19, 'НФ-201']]
dict_data = {}

for i in range(0,len(data)):
    dict_data[data[i][0]] = data[i][1:4]
    
dict_data

{1: ['Иванов', 18, 'НФ-101'],
 2: ['Свердлов', 20, 'НФ-301'],
 3: ['Сидоров', 19, 'НФ-201']}

In [13]:
#2. Добавьте к задаче No6 для словаря возможность (без преобразования словаря обратно в список) изменить группу
#студента. Поиск по «ФИО» («ФИО» студента и новый номер группы необходимо ввести с клавиатуры).
#3. Добавьте к задаче No6 для словаря возможность (без преобразования словаря обратно в список) изменить возраст
#студента.

name = input('Введите фамилию студента: ', )
number_of_group = input('Введите новый номер группы: ')
age = input('Введите новый возраст студента: ')

for keys, values in dict_data.items():
    if values[0] == name:
        values[2] = number_of_group
        try:
            if int(age) >= 17 and int(age) < 100:
                values[1] = int(age)
            else:
                print('Неверно введен возраст')
        except:
            print('Неверно введен возраст')
print(dict_data)

Введите фамилию студента: Свердлов
Введите новый номер группы: НФ-401
Введите новый возраст студента: 21
{1: ['Иванов', 18, 'НФ-101'], 2: ['Свердлов', 21, 'НФ-401'], 3: ['Сидоров', 19, 'НФ-201']}
