In [28]:
#Задание 1
#Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
import numpy as np

N = int(input('Введите N: ', ))
def reverse_array(N):
    array = np.arange( 0, N )
    reverse_array = np.flip(array, 0)
    #reverse_array = array[::-1] можно использовать такой более привычный способ
    return reverse_array

reverse_array(N)

Введите N: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [29]:
#Задание 2
#Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
diagonal_array = np.diag(reverse_array(N)) #создаем диагональную матрицу используя предыдущую функцию

sum(diagonal_array.diagonal()) #выводим array с элементами по диагонали и суммируем

print(diagonal_array, diagonal_array.diagonal(), sum(diagonal_array.diagonal()))

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]] [9 8 7 6 5 4 3 2 1 0] 45


In [5]:
#Задание 3
#Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера.
#Определите какому фильму было выставлено больше всего оценок 5.0.
import pandas as pd
movies = pd.read_csv('data/movies.csv')
ratings = pd.read_csv('data/ratings.csv')

In [6]:
movieId = ratings.loc[ratings['rating'] == 5].groupby('movieId').count().sort_values('rating', ascending=False).head(1).index[0]
count = ratings.loc[ratings['rating'] == 5].groupby('movieId').count().sort_values('rating', ascending=False).head(1).values[0][0]
#то есть наш искомый фильм имеет movieId 318 и количество оценок 5 равны 48762.
movieId, count

(318, 48762)

In [7]:
#c помощью такого запроса можно проверить правильно ли он посчитал количество оценок равных 5.
len(ratings.loc[ratings['movieId'] == 318].loc[ratings['rating'] == 5])

48762

In [8]:
name = movies.loc[movies['movieId'] == 318]['title'].values[0] #используя другую таблицу можно узнать название фильма (зная movieId)
name
# то есть наш фильм - это фильм "Побег из Шоушенка"

'Shawshank Redemption, The (1994)'

In [9]:
#Задание 4
#По данным файла power.csv посчитайте суммарное потребление стран Прибалтики
#(Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года.
#Не учитывайте в расчетах отрицательные значения quantity.

data = pd.read_csv('data/power.csv')

In [12]:
#чтобы запрос не был нечитабельным, лучше его разбить на несколько пунктов

filtered_countries = data[ (data['country']=='Latvia') | (data['country']=='Estonia') | (data['country']=='Lithuania')]

filtered_category = filtered_countries[ (filtered_countries['category'] == 21) | (filtered_countries['category'] == 12) | (filtered_countries['category'] == 4) ]

#будем учитывать 2005 и 2010 годы тоже, поэтому неравенства нестрогие
filtered_years = filtered_category[ (filtered_category['year'] >= 2005) & (filtered_category['year'] <= 2010) ]

filtered_quantity = filtered_years[ (filtered_years['quantity'] >= 0) ]

total_consumption = sum(filtered_quantity['quantity'].values)

print('Cуммарное потребление стран Прибалтики категорий 4, 12, 21 за период с 2005 по 2010: {}'.format(total_consumption))

Cуммарное потребление стран Прибалтики категорий 4, 12, 21 за период с 2005 по 2010: 240580.0


In [24]:
""" Задание 5
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3 """

from numpy import linalg

#составим для начала матрицу коэффициентов лин. сист. уравнений
A = np.array( [[4, 2, 1],
               [1, 3, 0],
               [0, 5, 4]])

#теперь составим столбец из значений в правой части уравнений
B = np.array( [4, 12, -3])

# решение с помощью метода solve
solution = linalg.solve(A, B)
print('Решение системы уравнений: x = {:.3}, y = {:.3}, z = {:.3}'.format(solution[0], solution[1], solution[2]))

Решение системы уравнений: x = 0.467, y = 3.84, z = -5.56


In [25]:
# проверка правильности: умножение матрицы коэфициентов на вектор-столбец решений = вектор-столбец B
np.allclose( np.dot(A, linalg.solve(A, B)), B )

True